import test from 'node:test';
import assert from 'node:assert/strict';
import { normalizeFx, quoteFx } from '../src/fx.js';
import { api } from '../worker/api.js';
const rows = ['KRW','USD','JPY','SGD','THB','AUD','CNY'].map((quote,i)=>({base:'EUR',quote,date:'2026-10-08',rate:[1500,1.1,175,1.4,37,1.6,7.5][i]}));
test('pivot preserves precision and source date',()=>{ const s=normalizeFx(rows,'2026-10-09T00:00:00Z'); assert.equal(quoteFx(s,'USD',['KRW'],Date.parse('2026-10-09')).rates.KRW,1500/1.1); });
test('missing, zero and duplicate rates rejected',()=>{ assert.throws(()=>normalizeFx(rows.slice(1))); assert.throws(()=>normalizeFx(rows.map((r,i)=>i===0?{...r,rate:0}:r))); assert.throws(()=>normalizeFx(rows.map((r,i)=>i===1?rows[0]:r))); });
test('expired snapshots cannot produce quotes',()=>assert.throws(()=>quoteFx(normalizeFx(rows),'KRW',['USD'],Date.parse('2026-10-17'))));
test('Worker serves local snapshot without any provider request',async()=>{ const old=globalThis.fetch; globalThis.fetch=()=>{throw Error('PROVIDER_ACCESS_FORBIDDEN')}; try{const r=await api(new Request('https://test/api/fx?base=USD&quotes=KRW')); const b=await r.json(); if(r.status===200){assert.equal(b.delivery,'local-runner-snapshot');assert.ok(b.rates.KRW>0);}else{assert.equal(r.status,503);assert.equal(b.rates,null);} const status=await api(new Request('https://test/api/status'));assert.equal((await status.json()).pipeline,'LOCAL_RUNNER_SNAPSHOT');}finally{globalThis.fetch=old;} });
test('invalid currency and absent advice stay explicit',async()=>{assert.equal((await api(new Request('https://test/api/fx?base=BAD'))).status,400);const r=await api(new Request('https://test/api/travel-advice?country=JP'));assert.equal(r.status,503);assert.equal((await r.json()).status,'UNVERIFIED');});
