import { japanEntry } from './japan-entry.js';
import { countries } from '../data/countries.js';
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function tripPage(request){
 const q=new URL(request.url).searchParams;const origin=q.get('origin'),destination=q.get('destination');
 const names=new Intl.DisplayNames(['ko'],{type:'region'});
 const valid=c=>/^[A-Z]{2}$/.test(c||'')&&names.of(c)!==c;
 if(!valid(origin)||!valid(destination)||origin===destination)return new Response('여행 경로를 다시 선택해주세요.',{status:400,headers:{'Content-Type':'text/plain; charset=utf-8'}});
 const name=c=>c==='KR'?'대한민국':names.of(c);const info=countries.find(c=>c.code===destination);
 const links=info?`<a href="${escape(info.entry)}" target="_blank" rel="noopener noreferrer" data-lr-text="8">입국 준비 공식 안내 ↗</a><a href="${escape(info.customs)}" target="_blank" rel="noopener noreferrer" data-lr-text="9">반입·세관 공식 안내 ↗</a>`:'<p data-lr-text="10">이 목적지의 입국·반입 공식 자료는 준비 중입니다.</p>';
 return new Response(`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" type="image/png" href="/assets/favicon-r2.png" sizes="128x128"><script defer src="/assets/language.js?v=bold-r6"></script><title>${escape(name(destination))} 여행 준비 · LandReady</title><link rel="stylesheet" href="/assets/lamdready.css?v=input-left-r21"><style>.lr-preparation{padding:32px;background:#fffffff2;border-radius:24px;box-shadow:0 18px 50px #173d4530}.lr-preparation h1{font-size:28px;letter-spacing:-1px;margin:0 0 12px}.lr-preparation p{font-size:15px;color:#526e74}.lr-preparation a{display:block;margin-top:14px;padding:15px;border:1px solid #d8e5e7;border-radius:12px;font-size:15px}.lr-preparation a:hover{background:#eaf3f4}#lr-app main{margin-top:100px}@media(max-width:600px){.lr-preparation{padding:16px}.lr-preparation h1{font-size:24px}#lr-app main{margin-top:24px}}</style></head><body><div id="lr-app"><header class="lr-header"><a class="lr-brand" href="https://landready.blogspot.com/" aria-label="LandReady 홈"><svg class="lr-logo" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><rect width="128" height="128" rx="32" fill="#164e5a"/><path d="M27 66 98 29 77 101 59 76Z" fill="#fff"/><path d="m59 76 39-47-29 54" fill="#99d9d2"/><circle cx="30" cy="100" r="6" fill="#d4ee91"/></svg><span>LandReady</span></a></header><main><section class="lr-preparation"><nav class="lr-trip-nav" aria-label="여행 경로"><a class="lr-trip-back" href="https://landready.blogspot.com/" aria-label="뒤로 가기" title="뒤로 가기"></a></nav>${origin==='KR'&&destination==='JP'?'':`<h1>${escape(name(destination))} 여행 준비</h1><p class="lr-route-summary">${escape(name(origin))} → ${escape(name(destination))}</p>`}${origin==='KR'&&destination==='JP'?japanEntry():links}<a href="https://www.0404.go.kr/" target="_blank" rel="noopener noreferrer" data-lr-text="11">외교부 해외안전여행 ↗</a><p data-lr-text="12">공식 정보를 확인하세요. 비자·입국·반입 허용 여부는 아직 자동 판정하지 않습니다.</p><a href="https://landready.blogspot.com/" data-lr-text="13">← 여행 경로 다시 선택</a></section></main></div></body></html>`,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Robots-Tag':'noindex','X-Content-Type-Options':'nosniff'}});
}

